server:
  servlet:
    context-path: /shop
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  redis:
    host: localhost
    port: 6379
    password: foobared
  session:
    store-type: redis
    redis:
      save-mode: always
      flush-mode: immediate
