server:
  servlet:
    context-path: /shop
  port: 8191
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:users_db;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  redis:
    host: localhost
    port: 6379
    password: foobared
  session:
    store-type: redis
    redis:
      save-mode: always
      flush-mode: immediate
