server:
  port: 0
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:users_db;MODE=PostgreSQL
    username: sa
    password:
  application:
    name: ms-auth
  h2:
    console:
      enabled: true
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
    fetch-registry: true
