server:
  servlet:
    context-path: /shop
  port: 8189
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:product_db;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true


